const Results2022Array = [
  {
    tour: 1,
    day: 26,
    month: "февраля",
    dudaMainScore: 3,
    rayMainScore: 6,
    matches: [
      {
        matchNumber: 1,
        team1Name: "Реал",
        team2Name: "Челси",
        team1Score: 0,
        team2Score: 1,
      },
      {
        matchNumber: 2,
        team1Name: "МЮ",
        team2Name: "ПСЖ",
        team1Score: 0,
        team2Score: 3,
      },
      {
        matchNumber: 3,
        team1Name: "Челси",
        team2Name: "Реал",
        team1Score: 0,
        team2Score: 3,
      },
      {
        matchNumber: 4,
        team1Name: "Атлетико",
        team2Name: "Бавария",
        team1Score: 3,
        team2Score: 2,
      },
      {
        matchNumber: 5,
        team1Name: "Реал",
        team2Name: "ПСЖ",
        team1Score: 1,
        team2Score: 3,
      },
      {
        matchNumber: 6,
        team1Name: "МЮ",
        team2Name: "Ливерпуль",
        team1Score: 4,
        team2Score: 2,
      },
      {
        matchNumber: 7,
        team1Name: "Бавария",
        team2Name: "Реал",
        team1Score: 1,
        team2Score: 3,
      },
      {
        matchNumber: 8,
        team1Name: "ПСЖ",
        team2Name: "МЮ",
        team1Score: 0,
        team2Score: 2,
      },
      {
        matchNumber: 9,
        team1Name: "Атлетико",
        team2Name: "Арсенал",
        team1Score: 6,
        team2Score: 2,
      },
      {
        matchNumber: 10,
        team1Name: "Атлетико",
        team2Name: "ПСЖ",
        team1Score: 3,
        team2Score: 3,
      },
    ],
    dudaGoalsQty: 18,
    rayGoalsQty: 24,
  },
  {
    tour: 2,
    day: 12,
    month: "марта",
    dudaMainScore: 3,
    rayMainScore: 1,
    matches: [
      {
        matchNumber: 1,
        team1Name: "Атлетико",
        team2Name: "ПСЖ",
        team1Score: 2,
        team2Score: 2,
      },
      {
        matchNumber: 2,
        team1Name: "Реал",
        team2Name: "МЮ",
        team1Score: 1,
        team2Score: 1,
      },
      {
        matchNumber: 3,
        team1Name: "МЮ",
        team2Name: "Челси",
        team1Score: 3,
        team2Score: 2,
      },
      {
        matchNumber: 4,
        team1Name: "Бавария",
        team2Name: "Реал",
        team1Score: 5,
        team2Score: 0,
      },
      {
        matchNumber: 5,
        team1Name: "Атлетико",
        team2Name: "ПСЖ",
        team1Score: 0,
        team2Score: 3,
      },
      {
        matchNumber: 6,
        team1Name: "Челси",
        team2Name: "Тоттенхэм",
        team1Score: 5,
        team2Score: 3,
      },
      {
        matchNumber: 7,
        team1Name: "Арсенал",
        team2Name: "МС",
        team1Score: 2,
        team2Score: 2,
      },
    ],
    dudaGoalsQty: 18,
    rayGoalsQty: 13,
  },
  {
    tour: 3,
    day: 10,
    month: "апреля",
    dudaMainScore: 3,
    rayMainScore: 4,
    matches: [
      {
        matchNumber: 1,
        team1Name: "Бавария",
        team2Name: "ПСЖ",
        team1Score: 2,
        team2Score: 1,
      },
      {
        matchNumber: 2,
        team1Name: "Реал",
        team2Name: "МЮ",
        team1Score: 0,
        team2Score: 1,
      },
      {
        matchNumber: 3,
        team1Name: "Атлетико",
        team2Name: "Ливерпуль",
        team1Score: 1,
        team2Score: 3,
      },
      {
        matchNumber: 4,
        team1Name: "МЮ",
        team2Name: "Реал",
        team1Score: 0,
        team2Score: 1,
      },
      {
        matchNumber: 5,
        team1Name: "Челси",
        team2Name: "МС",
        team1Score: 1,
        team2Score: 3,
      },
      {
        matchNumber: 6,
        team1Name: "МЮ",
        team2Name: "Ливерпуль",
        team1Score: 3,
        team2Score: 2,
      },
      {
        matchNumber: 7,
        team1Name: "Бавария",
        team2Name: "ПСЖ",
        team1Score: 3,
        team2Score: 1,
      },
    ],
    dudaGoalsQty: 10,
    rayGoalsQty: 12,
  },
  {
    tour: 4,
    day: 20,
    month: "мая",
    dudaMainScore: 2,
    rayMainScore: 2,
    matches: [
      {
        matchNumber: 1,
        team1Name: "МЮ",
        team2Name: "ПСЖ",
        team1Score: 3,
        team2Score: 1,
      },
      {
        matchNumber: 2,
        team1Name: "Бавария",
        team2Name: "Ливерпуль",
        team1Score: 1,
        team2Score: 1,
      },
      {
        matchNumber: 3,
        team1Name: "Реал",
        team2Name: "МЮ",
        team1Score: 0,
        team2Score: 4,
      },
      {
        matchNumber: 4,
        team1Name: "МЮ",
        team2Name: "МС",
        team1Score: 2,
        team2Score: 4,
      },
      {
        matchNumber: 5,
        team1Name: "Бавария",
        team2Name: "Челси",
        team1Score: 2,
        team2Score: 1,
      },
      {
        matchNumber: 6,
        team1Name: "МЮ",
        team2Name: "Реал",
        team1Score: 2,
        team2Score: 2,
      },
    ],
    dudaGoalsQty: 10,
    rayGoalsQty: 13,
  },
  {
    tour: "ТОВАРНЯК",
    day: 9,
    month: "октября",
    dudaMainScore: 0,
    rayMainScore: 5,
    matches: [],
  },
  {
    tour: "ТОВАРНЯК",
    day: 29,
    month: "октября",
    dudaMainScore: 0,
    rayMainScore: 5,
    matches: [],
  },
  {
    tour: 5,
    day: 9,
    month: "ноября",
    dudaMainScore: 3,
    rayMainScore: 4,
    matches: [
      {
        matchNumber: 1,
        team1Name: "Реал",
        team2Name: "ПСЖ",
        team1Score: 2,
        team2Score: 0,
      },
      {
        matchNumber: 2,
        team1Name: "Бавария",
        team2Name: "Ливерпуль",
        team1Score: 2,
        team2Score: 2,
      },
      {
        matchNumber: 3,
        team1Name: "МЮ",
        team2Name: "МС",
        team1Score: 2,
        team2Score: 3,
      },
      {
        matchNumber: 4,
        team1Name: "Атлетико",
        team2Name: "МЮ",
        team1Score: 2,
        team2Score: 2,
      },
      {
        matchNumber: 5,
        team1Name: "Наполи",
        team2Name: "Реал",
        team1Score: 1,
        team2Score: 5,
      },
      {
        matchNumber: 6,
        team1Name: "Тоттенхэм",
        team2Name: "Барселона",
        team1Score: 1,
        team2Score: 2,
      },
      {
        matchNumber: 7,
        team1Name: "Реал",
        team2Name: "Бавария",
        team1Score: 1,
        team2Score: 1,
      },
      {
        matchNumber: 8,
        team1Name: "Бавария",
        team2Name: "Челси",
        team1Score: 3,
        team2Score: 2,
      },
      {
        matchNumber: 9,
        team1Name: "Реал",
        team2Name: "ПСЖ",
        team1Score: 0,
        team2Score: 4,
      },
      {
        matchNumber: 8,
        team1Name: "МЮ",
        team2Name: "Ливерпуль",
        team1Score: 3,
        team2Score: 1,
      },
      {
        matchNumber: 9,
        team1Name: "Милан",
        team2Name: "Арсенал",
        team1Score: 2,
        team2Score: 2,
      },
      {
        matchNumber: 8,
        team1Name: "МЮ",
        team2Name: "МС",
        team1Score: 3,
        team2Score: 3,
      },
      {
        matchNumber: 9,
        team1Name: "Бавария",
        team2Name: "ПСЖ",
        team1Score: 1,
        team2Score: 1,
      },
    ],
    dudaGoalsQty: 23,
    rayGoalsQty: 28,
  },
  {
    tour: 6,
    day: 16,
    month: "ноября",
    dudaMainScore: 5,
    rayMainScore: 11,
    matches: [
      {
        matchNumber: 1,
        team1Name: "Бавария",
        team2Name: "ПСЖ",
        team1Score: 2,
        team2Score: 4,
      },
      {
        matchNumber: 2,
        team1Name: "МЮ",
        team2Name: "Реал",
        team1Score: 1,
        team2Score: 2,
      },
      {
        matchNumber: 3,
        team1Name: "Реал",
        team2Name: "МЮ",
        team1Score: 3,
        team2Score: 1,
      },
      {
        matchNumber: 4,
        team1Name: "Ювентус",
        team2Name: "МС",
        team1Score: 1,
        team2Score: 1,
      },
      {
        matchNumber: 5,
        team1Name: "Бавария",
        team2Name: "Бавария",
        team1Score: 0,
        team2Score: 8,
      },
      {
        matchNumber: 6,
        team1Name: "Португалия",
        team2Name: "Франция",
        team1Score: 1,
        team2Score: 1,
      },
      {
        matchNumber: 7,
        team1Name: "Атлетико",
        team2Name: "Ливерпуль",
        team1Score: 2,
        team2Score: 3,
      },
      {
        matchNumber: 8,
        team1Name: "Реал",
        team2Name: "Тоттенхэм",
        team1Score: 2,
        team2Score: 3,
      },
      {
        matchNumber: 9,
        team1Name: "Интер",
        team2Name: "Лестер",
        team1Score: 3,
        team2Score: 2,
      },
      {
        matchNumber: 10,
        team1Name: "ПСЖ",
        team2Name: "Ювентус",
        team1Score: 3,
        team2Score: 1,
      },
      {
        matchNumber: 11,
        team1Name: "Реал",
        team2Name: "Бавария",
        team1Score: 1,
        team2Score: 1,
      },
      {
        matchNumber: 12,
        team1Name: "Реал",
        team2Name: "Бавария",
        team1Score: 3,
        team2Score: 3,
      },
      {
        matchNumber: 13,
        team1Name: "МЮ",
        team2Name: "ПСЖ",
        team1Score: 2,
        team2Score: 3,
      },
      {
        matchNumber: 14,
        team1Name: "Челси",
        team2Name: "Ливерпуль",
        team1Score: 5,
        team2Score: 2,
      },
      {
        matchNumber: 15,
        team1Name: "Милан",
        team2Name: "МС",
        team1Score: 3,
        team2Score: 5,
      },
      {
        matchNumber: 16,
        team1Name: "Бельгия",
        team2Name: "Португалия",
        team1Score: 3,
        team2Score: 5,
      },
      {
        matchNumber: 17,
        team1Name: "ПСЖ",
        team2Name: "МЮ",
        team1Score: 0,
        team2Score: 3,
      },
      {
        matchNumber: 18,
        team1Name: "Бавария",
        team2Name: "Тоттенхэм",
        team1Score: 0,
        team2Score: 4,
      },
      {
        matchNumber: 19,
        team1Name: "Челси",
        team2Name: "Арсенал",
        team1Score: 3,
        team2Score: 2,
      },
      {
        matchNumber: 20,
        team1Name: "Реал",
        team2Name: "ПСЖ",
        team1Score: 3,
        team2Score: 4,
      },
    ],
    dudaGoalsQty: 41,
    rayGoalsQty: 60,
  },
  {
    tour: 7,
    day: 29,
    month: "ноября",
    dudaMainScore: 3,
    rayMainScore: 6,
    matches: [
      {
        matchNumber: 1,
        team1Name: "Реал",
        team2Name: "ПСЖ",
        team1Score: 5,
        team2Score: 3,
      },
      {
        matchNumber: 2,
        team1Name: "Челси",
        team2Name: "МС",
        team1Score: 3,
        team2Score: 3,
      },
      {
        matchNumber: 3,
        team1Name: "Ювентус",
        team2Name: "Бавария",
        team1Score: 1,
        team2Score: 3,
      },
      {
        matchNumber: 4,
        team1Name: "Ювентус",
        team2Name: "МС",
        team1Score: 1,
        team2Score: 1,
      },
      {
        matchNumber: 5,
        team1Name: "МЮ",
        team2Name: "Барселона",
        team1Score: 2,
        team2Score: 1,
      },
      {
        matchNumber: 6,
        team1Name: "Бавария",
        team2Name: "Реал",
        team1Score: 1,
        team2Score: 1,
      },
      {
        matchNumber: 7,
        team1Name: "ПСЖ",
        team2Name: "МЮ",
        team1Score: 2,
        team2Score: 1,
      },
      {
        matchNumber: 8,
        team1Name: "Милан",
        team2Name: "Ливерпуль",
        team1Score: 0,
        team2Score: 2,
      },
      {
        matchNumber: 9,
        team1Name: "Атлетико",
        team2Name: "Тоттенхэм",
        team1Score: 4,
        team2Score: 4,
      },
      {
        matchNumber: 10,
        team1Name: "Испания",
        team2Name: "Франция",
        team1Score: 1,
        team2Score: 2,
      },
      {
        matchNumber: 11,
        team1Name: "Интер",
        team2Name: "Арсенал",
        team1Score: 2,
        team2Score: 3,
      },
      {
        matchNumber: 12,
        team1Name: "Ливерпуль",
        team2Name: "Атлетико",
        team1Score: 1,
        team2Score: 4,
      },
      {
        matchNumber: 13,
        team1Name: "Наполи",
        team2Name: "Интер",
        team1Score: 2,
        team2Score: 2,
      },
      {
        matchNumber: 14,
        team1Name: "Реал",
        team2Name: "ПСЖ",
        team1Score: 2,
        team2Score: 6,
      },
    ],
    dudaGoalsQty: 26,
    rayGoalsQty: 35,
  },
  {
    tour: 8,
    day: 7,
    month: "декабря",
    dudaMainScore: 5,
    rayMainScore: 7,
    matches: [
      {
        matchNumber: 1,
        team1Name: "ПСЖ",
        team2Name: "Бавария",
        team1Score: 2,
        team2Score: 0,
      },
      {
        matchNumber: 2,
        team1Name: "Реал",
        team2Name: "ПСЖ",
        team1Score: 3,
        team2Score: 3,
      },
      {
        matchNumber: 3,
        team1Name: "Барселона",
        team2Name: "МЮ",
        team1Score: 1,
        team2Score: 1,
      },
      {
        matchNumber: 4,
        team1Name: "Бавария",
        team2Name: "Тоттенхэм",
        team1Score: 3,
        team2Score: 1,
      },
      {
        matchNumber: 5,
        team1Name: "Атлетико",
        team2Name: "Реал",
        team1Score: 1,
        team2Score: 0,
      },
      {
        matchNumber: 6,
        team1Name: "Челси",
        team2Name: "МС",
        team1Score: 2,
        team2Score: 2,
      },
      {
        matchNumber: 7,
        team1Name: "МЮ",
        team2Name: "Барселона",
        team1Score: 2,
        team2Score: 3,
      },
      {
        matchNumber: 8,
        team1Name: "Аргентина",
        team2Name: "Англия",
        team1Score: 1,
        team2Score: 4,
      },
      {
        matchNumber: 9,
        team1Name: "Милан",
        team2Name: "Ливерпуль",
        team1Score: 3,
        team2Score: 3,
      },
      {
        matchNumber: 10,
        team1Name: "Ювентус",
        team2Name: "Атлетико",
        team1Score: 1,
        team2Score: 5,
      },
      {
        matchNumber: 11,
        team1Name: "Реал",
        team2Name: "ПСЖ",
        team1Score: 1,
        team2Score: 0,
      },
      {
        matchNumber: 12,
        team1Name: "Реал",
        team2Name: "Бавария",
        team1Score: 1,
        team2Score: 4,
      },
      {
        matchNumber: 13,
        team1Name: "Челси",
        team2Name: "Арсенал",
        team1Score: 2,
        team2Score: 2,
      },
      {
        matchNumber: 14,
        team1Name: "Испания",
        team2Name: "Франция",
        team1Score: 3,
        team2Score: 2,
      },
      {
        matchNumber: 15,
        team1Name: "Бавария",
        team2Name: "Тоттенхэм",
        team1Score: 2,
        team2Score: 4,
      },
      {
        matchNumber: 16,
        team1Name: "Реал",
        team2Name: "Барселона",
        team1Score: 1,
        team2Score: 1,
      },
      {
        matchNumber: 17,
        team1Name: "МЮ",
        team2Name: "МС",
        team1Score: 2,
        team2Score: 4,
      },
    ],
    dudaGoalsQty: 30,
    rayGoalsQty: 39,
  },
  {
    tour: 9,
    day: 27,
    month: "декабря",
    dudaMainScore: 9,
    rayMainScore: 5,
    matches: [
      {
        matchNumber: 1,
        team1Name: "Реал",
        team2Name: "ПСЖ",
        team1Score: 0,
        team2Score: 2,
      },
      {
        matchNumber: 2,
        team1Name: "ПСЖ",
        team2Name: "Тоттенхэм",
        team1Score: 4,
        team2Score: 3,
      },
      {
        matchNumber: 3,
        team1Name: "МЮ",
        team2Name: "МС",
        team1Score: 3,
        team2Score: 1,
      },
      {
        matchNumber: 4,
        team1Name: "Челси",
        team2Name: "Бавария",
        team1Score: 0,
        team2Score: 5,
      },
      {
        matchNumber: 5,
        team1Name: "Бавария",
        team2Name: "Реал",
        team1Score: 5,
        team2Score: 1,
      },
      {
        matchNumber: 6,
        team1Name: "Барселона",
        team2Name: "Ливерпуль",
        team1Score: 3,
        team2Score: 4,
      },
      {
        matchNumber: 7,
        team1Name: "Италия",
        team2Name: "Франция",
        team1Score: 2,
        team2Score: 3,
      },
      {
        matchNumber: 8,
        team1Name: "ЦСКА",
        team2Name: "МЮ",
        team1Score: 2,
        team2Score: 1,
      },
      {
        matchNumber: 9,
        team1Name: "Бенфика",
        team2Name: "Лестер",
        team1Score: 0,
        team2Score: 5,
      },
      {
        matchNumber: 10,
        team1Name: "Атлетико",
        team2Name: "Барселона",
        team1Score: 2,
        team2Score: 1,
      },
      {
        matchNumber: 11,
        team1Name: "Реал",
        team2Name: "ПСЖ",
        team1Score: 5,
        team2Score: 3,
      },
      {
        matchNumber: 12,
        team1Name: "Реал",
        team2Name: "ПСЖ",
        team1Score: 1,
        team2Score: 0,
      },
      {
        matchNumber: 13,
        team1Name: "ПСЖ",
        team2Name: "Бавария",
        team1Score: 4,
        team2Score: 3,
      },
      {
        matchNumber: 14,
        team1Name: "Бавария",
        team2Name: "Тоттенхэм",
        team1Score: 6,
        team2Score: 1,
      },
    ],
    dudaGoalsQty: 37,
    rayGoalsQty: 33,
  },
];

export default Results2022Array;
